export const reviews = [
	{
		id: 1,
		name: "John Doe",
		rating: 5,
		comment:
			"Amazing experience! The farm tour was educational and fun for the whole family.",
	},
	// ... other reviews
];

export const products = [
	{
		id: 1,
		name: "Apricot",
		category: "FRESH FRUIT",
		price: 49.0,
		oldPrice: 65.0,
		image: "/images/products/apricot.jpg",
		isNew: false,
		isSale: false,
	},
	{
		id: 2,
		name: "Banana",
		category: "FRESH FRUIT",
		price: 32.0,
		oldPrice: 45.0,
		image: "/images/products/banana.jpg",
		isNew: false,
		isSale: false,
	},
	{
		id: 3,
		name: "Black Berry",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/blackberry.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 4,
		name: "Blue Barry",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/blueberry.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 5,
		name: "Cherry",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/cherry.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 6,
		name: "Kiwi",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/kiwi.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 7,
		name: "Orange",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/orange.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 8,
		name: "Pineapple",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/pineapple.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 9,
		name: "Rose Berry",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/rose berry.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 10,
		name: "Strawberry",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/strawberry.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 11,
		name: "Watermelon",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/watermelon.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	{
		id: 12,
		name: "Plum",
		category: "FRESH FRUIT",
		price: 25.0,
		oldPrice: 35.0,
		image: "/images/products/images.jpg",
		weight: "500 g",
		isNew: false,
		isSale: false,
	},
	// ... other products
];

export const news = [
	{
		id: 1,
		title: "New Educational Programs Launch",
		date: "2024-03-15",
		summary:
			"Introducing our new series of educational programs for schools and families.",
	},
	// ... other news items
];
